Issue-49 fix - add prefix to `owner` attribute
DmitryTsepelev/ar_lazy_preload pull request #50
Opened 2021-05-12 14:19 UTC by RuslanKhabibullin

https://github.com/DmitryTsepelev/ar_lazy_preload/issues/49

2021-05-13 02:38 UTC, PikachuEXE commented
Would be good to have test cases that reproduce what's fixed

2021-05-13 09:52 UTC, RuslanKhabibullin commented
@PikachuEXE I've added a simple spec that checks that there are no exceptions for entities with `owner` enum value. An error can be reproduced with the next `Gemfile.local` file + old `AssociationRelation` class (with `owner` delegation without prefix):

```
source 'https://rubygems.org'

gem "sqlite3", "~> 1.4"
gem "rails", "~> 6.1.1"
```

2021-05-17 05:52 UTC, DmitryTsepelev requested changes
Hi @RuslanKhabibullin, thank you for the PR!

Let's fix RuboCop, couple of questions in below, please add yourself to the changelog and we'll be good to go.

2021-05-17 05:52 UTC, DmitryTsepelev commented on spec/ar_lazy_preload/active_record/association_relation_spec.rb
> +  end
```suggestion
  let(:club) { create(:club) }
  let(:user) { create(:user) }
  
  before do
    create :club_member, club: club, user: user, role: :owner
  end
```

2021-05-17 05:52 UTC, DmitryTsepelev commented on spec/ar_lazy_preload/active_record/association_relation_spec.rb
> +    expect { p user.club_memberships }.not_to raise_error
Can we replace `user.club_memberships` with `user.club_memberships.load` ?

2021-05-17 08:25 UTC, RuslanKhabibullin commented
@DmitryTsepelev thank you for your review! Seems like done.

2021-05-18 15:48 UTC, DmitryTsepelev approved these changes

2021-05-18 15:54 UTC, merged